### ISSUE TITLE
Public or private?

### ISSUE THREAD

**Issue by abrothman-vacatia** [willemverspyck/snowflake-sdk-php#1]
README says:

>**2. Set the public key in Snowflake for the user:**
>Set the public key for the user who will connect with the Snowflake API. Make sure that you put your own public key (rsa_key.pub) in a single line.

```ALTER USER <username> SET rsa_public_key = '<publicKey>';```

>**3. Get public key from Snowflake:**
>Run the describe command for the user to get the RSA_PUBLIC_KEY_FP.

```DESC USER <username>;```

And then later:

```
# Public key from step 3
$client->setPublicKey('<publicKey>');
```
So, are we supposed to provide a key, a file path, or a fingerprint?

From `Client.php`, it appears that we're looking for a file, but...

```
    public function setPublicKey(string $publicKey): self
    {
        if (file_exists($publicKey)) {
            throw new ParameterException(sprintf('Public key "%s" not found', $publicKey));
        }

        $this->publicKey = $publicKey;

        return $this;
    }
```

Should that be checking for the _lack_ of the file, not it's presence?

**Comment by willemverspyck** [comment]
Hi @abrothman-vacatia,

> So, are we supposed to provide a key, a file path, or a fingerprint?

You have to provide a key in this step (as string). To be precise, the "public key" retrieved from the query in step 3.

> Should that be checking for the lack of the file, not it's presence?

You are right. That is an incorrect check. The idea was to check if the file exists and then put the content in $this->publicKey, but that doesn't work this way. I will fix that soon, but you can pass it as string. That works :-)
